// frontpunto/src/components/Button.jsx
export const Button = ({onClick, children, extraCls=""}) => {
    return (
        <button type="submit"
                className={`
                bg-red-400
                p-2 
                rounded
                hover:cursor-pointer
                hover:opacity-75
                text-white
                ${extraCls}
        `}
        onClick={onClick}
        >{children}</button>
    )
}

// frontpuntoang/src/app/presentation/components/atoms/button/button.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';

@Component({
  selector: 'button-atom',
  imports: [],
  templateUrl: './button.component.html',
  styleUrl: './button.component.scss'
})
export class ButtonComponent {
  @Input() type : "submit" | "button" = "button";
  @Input() text : string = "Click btn";
  @Output() onClick = new EventEmitter<void>()
}

<button class="
    w-full
    rounded
    p-2
    bg-red-400
    text-white
    hover:opacity-75
    "
    [type]="type"
    (click)="onClick.emit()"
>{{text}}</button>
